### ISSUE TITLE
[BUG] Actualizar datos Panel

### ISSUE THREAD

**Issue by Enyel04** [Jamester-Cloud/AlcoEmpleo#6]
**Describe el Bug 1#**
Los numeros de telefono no se actualizan y debe de colocarse el +58 para que se redirige hacia el whatsapp, y al darle eliminar no eliminan, siguen ahí

![image](https://github.com/user-attachments/assets/972847f8-c137-4b71-905c-85de652331b4)

**Pasos de Reproducción**
Anotar anotar el numero y al darle enter deberia de actualizar, muestra el mensaje, pero no lo actualiza

**Describe el Bug 2#**

No actualizan los textos de Banner
![image](https://github.com/user-attachments/assets/592e937d-21c1-4d98-b6d1-095da04a76e0)

**Describe el Bug 3#**
tratar de actualizar los datos y actualizan unos, pero otros no

![image](https://github.com/user-attachments/assets/5e10f2ec-17c4-4128-8393-4f411da9c008)

Observa aca como se ve Posteado
![image](https://github.com/user-attachments/assets/a67fb2b3-ccd5-4b45-997c-17e9ab1d3842)

**Pasos de Reproducción**
Actualizar el 2do Titulo de Seccion esta ocasionando cierto bug, y no actualiza la siguiente página

**Comment by Jamester-Cloud** [comment]
Ahora los modelos se crean solos. Pienso que pueden ser por las doble sesiones, se deben realizar mas pruebas en la edicion del homepage
